// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicRandomPadRow,
  DefaultRandomPadRowProps
} from "./plasmic/jamesarmenta/PlasmicRandomPadRow";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface RandomPadRowProps extends DefaultRandomPadRowProps {}

function RandomPadRow_(props: RandomPadRowProps, ref: HTMLElementRefOf<"div">) {
  const [paddingStyles, setPaddingStyles] = React.useState({});

  React.useLayoutEffect(() => {
    const isMobile = window.innerWidth < 800;
    const MAX_AMOUNT = isMobile ? 10 : 30;
    
    const paddingAmount = Math.floor(Math.random() * MAX_AMOUNT);
    const paddingDirection = Math.random() > 0.5 ? "paddingLeft" : "paddingRight";

    const nextPaddingStyles: {[key: string]: string} = {};
    nextPaddingStyles[paddingDirection] = paddingAmount + "%";

    setPaddingStyles(nextPaddingStyles);
  }, []);

  const overrides = {
    root: {
      style: {
        ...paddingStyles
      }
    }
  };

  return <PlasmicRandomPadRow root={{ ref }} {...props} overrides={overrides} />;
}

const RandomPadRow = React.forwardRef(RandomPadRow_);
export default RandomPadRow;
